### ISSUE TITLE
vercel feature flags

### ISSUE THREAD

**Issue by lifeiscontent** [vercel/remix#101]
any plans to support Vercel Feature Flags so that it works with remix? I noticed the docs are pretty bare outside of Next.js ecosystem.

**Comment by TooTallNate** [comment]
Was there something Remix-specific that you are looking for? The [`@vercel/flags` package](https://vercel.com/docs/workflow-collaboration/feature-flags/vercel-flags) should work in your `loader`/`action` functions already. Let me know if you are running into any issues though.

**Comment by TooTallNate** [comment]
I created an example repo to show how to use `@vercel/flags` with Remix via just the Vercel toolbar (no provider): https://github.com/TooTallNate/remix-feature-flags/tree/main/app

**Comment by lifeiscontent** [comment]
@TooTallNate thank you for your help :)

**Comment by lifeiscontent** [comment]
@TooTallNate FlagValues component doesn't accept a nonce parameter, so far that's been my only issue.

**Comment by lifeiscontent** [comment]
nvm, I realized remix is using the `cookie` package under the hood and they're doing some extra magic on top with `createCookie`

**Comment by TooTallNate** [comment]
I pushed some improvements after reading through the Vercel Feature Flags documentation some more. You can now add metadata like a description and link to the flags in the toolbar, and the toolbar is loaded during development as well.

I'll close out this issue now.
