### ISSUE TITLE
how can I gracefully handle FUNCTION_INVOCATION_TIMEOUT

### ISSUE THREAD

**Issue by lifeiscontent** [vercel/remix#102]
using the following snippet, can someone show me how I would handle these kinds of errors?

from what I can tell, it would fall within the `else` block, but I'd like to instruct the user to refresh instead of showing `Unknown Error`

```tsx
import {
  isRouteErrorResponse,
  useRouteError,
} from "@remix-run/react";

export function ErrorBoundary() {
  const error = useRouteError();

  if (isRouteErrorResponse(error)) {
    return (
      <div>
        <h1>
          {error.status} {error.statusText}
        </h1>
        <p>{error.data}</p>
      </div>
    );
  } else if (error instanceof Error) {
    return (
      <div>
        <h1>Error</h1>
        <p>{error.message}</p>
        <p>The stack trace is:</p>
        <pre>{error.stack}</pre>
      </div>
    );
  } else {
    return <h1>Unknown Error</h1>;
  }
}
```

**Comment by TooTallNate** [comment]
I'm not sure that it would be possible tbh. A function timeout means that no HTTP response was sent before the timeout occurred. So it's not really the same as a thrown error in a sub route.

**Comment by lifeiscontent** [comment]
ah, right, that makes sense. 😅 Thanks for clarifying.
