### ISSUE TITLE
Root route imports are always bundled for edge

### ISSUE THREAD

**Issue by DuncanLHS** [vercel/remix#106]
As a result of issues with unsupported modules similar to #94 and #104 (in my case the problem is tailwind-merge) I've been trying to avoid edge and have everything run in node for the time being. However, as soon as I start adding UI to my root file I get the unsupported module errors back again due to the tailwind-merge module.

It looks like everything in root.tsx is being bundled for the edge runtime. adding `export const config = { runtime: "nodejs" }` to root.tsx has no impact and is ignored.

Is this intended default behaviour? How to get around it?

**Comment by TooTallNate** [comment]
The root layout is indeed included for all leaf routes. If you have some common layout which is using modules that are not supported on Edge runtime, consider defining a [pathless layout](https://remix.run/docs/en/main/file-conventions/routes#nested-layouts-without-nested-urls) which has `export const config = { runtime: "nodejs" }` and then you could nest any routes which use that layout underneath that pathless layout.
