### ISSUE TITLE
2.9.1?

### ISSUE THREAD

**Issue by pwbriggs** [vercel/remix#108]
As you may be aware, remix just published a patch release, `2.9.1`. Because of the peer dependency `@vercel/remix@2.9.0` &lrarr; `@remix-run/dev@2.9.0`, I'm getting dependency tree resolution errors (Vercel seems to be injecting `@vercel/remix` as part of the build process? It's not explicitly declared in my `package.json`).

I don't see a `@vercel/remix@2.9.0` on the npm registry yet, so I just wanted to check in.

**Comment by lifeiscontent** [comment]
@pwbriggs you can install this version of `@vercel/remix` to try it out: `https://remix-git-fork-lifeiscontent-chore-bump-release.vercel.sh/vercel-remix.tgz` its built via this PR: #110

**Comment by TooTallNate** [comment]
2.9.1 published

> Vercel seems to be injecting `@vercel/remix` as part of the build process?

Btw, are you using Remix + Vite yet? If not, I strongly suggest that you migrate to that.

**Comment by pwbriggs** [comment]
Nice, thanks!

> are you using Remix + Vite yet?

I just saw this in the documentation. Sounds exciting!
