### ISSUE TITLE
Deploying remix vite to vercel error

### ISSUE THREAD

**Issue by pullmann4rent** [vercel/remix#118]
Hello,

I want to deploy my remix vite app to vercel but I got following errorr:

```
x Build failed in 128ms
[commonjs--resolver] Server-only module referenced by client
```

what I am doing wrong ?

I followed this tutorial https://vercel.com/changelog/support-for-remix-with-vite

but didnt work

**Comment by TooTallNate** [comment]
This would be a more general Remix error related to your application code, not specific to Vercel.

But the error message is saying that you have client code that's importing a `.server` module, which isn't allowed. Perhaps the suggestions in this thread can help: https://github.com/remix-run/remix/discussions/9035
