### ISSUE TITLE
Missing unstable_data from @remix-run/node

### ISSUE THREAD

**Issue by paul-vd** [vercel/remix#128]
The unstable [`unstable_data`](https://remix.run/docs/en/main/utils/data) export is missing.

- [changelog](https://github.com/remix-run/remix/blob/7c0366fc73e513f55fe643291d1b5669d62ad13d/CHANGELOG.md#v2110)

**Comment by EndangeredMassa** [comment]
Will follow up here: https://github.com/vercel/remix/pull/127
