### ISSUE TITLE
Cannot return multiple "Set-Cookie" headers in actions/loaders

### ISSUE THREAD

**Issue by cody-dot-js** [vercel/remix#130]
I am noticing that when I run remix vite locally with single fetch, I can return multiple `Set-Cookie` headers in actions and loaders. If I do something like:

```ts
const headers = new Headers([
  ["Set-Cookie", "aaa=1"],
  ["Set-Cookie", "bbb=1"],
  ["Set-Cookie", "ccc=1"],
]);

return redirect("/somewhere", { headers });
```

I see all three `Set-Cookie` headers sent to the browser.

However, when deployed to vercel, only the last `Set-Cookie` header `"ccc=1"` is sent to the browser! I am not sure at this time if it's a purely vercel serverless runtime bug or a wombo combo with vercel + remix vite + single-fetch.

I am using node 20 lts and the latest versions of remix, vite, and the vercel preset.

I am working on producing a minimal repro case for y'all and will update this issue when I have one. I will also investigate if it's a problem with the classic remix compiler and remix vite without single fetch enabled. 

EDIT:
Reproduction repo: https://github.com/cody-dot-js/remix-vercel-set-cookie-repro
Reproduction deployment: https://remix-vercel-set-cookie-repro.vercel.app/

Expectation:
I see three cookies set when I visit the index page of this app: `aaa=loader`, `bbb=loader`, and `ccc=loader`.

I see three `Set-Cookie` headers in the network tab for the action response.

Reality:
Locally, I see the three cookies.
However, in the vercel deployment, I only see the last cookie `ccc=loader`

Screenshots:

![Google Chrome 2024-09-10 13 57 33](https://github.com/user-attachments/assets/f33a56f5-ab87-486c-9fe3-080e98b2c6c7)

![Google Chrome 2024-09-10 13 59 02](https://github.com/user-attachments/assets/2f278ef4-6030-4d9d-8e40-06ce9830458b)

**Comment by cody-dot-js** [comment]
Looks like it's a bug w/ remix single fetch on vercel!

Repro here:
https://github.com/cody-dot-js/remix-vercel-set-cookie-repro/pull/1

Deploy:
https://remix-vercel-set-cookie-rep-git-fcb2b2-codyjs-projects-9c03697f.vercel.app/

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/47f9704f-a904-4ad6-a3c5-3ac0896314b7">

**Comment by TooTallNate** [comment]
This should be fixed as of ~a month ago. Please open a new issue if you are still having issues.
