### ISSUE TITLE
Vercel cache always misses when using Link

### ISSUE THREAD

**Issue by mikkel-arturo** [vercel/remix#133]
I have a Remix application deployed on vercel with the following header configuration
```
export const headers: HeadersFunction = () => ({
  'Cache-Control': 'public, max-age=0, s-maxage=600, stale-while-revalidate=60',
  Vary: 'Accept-Encoding, User-Agent',
})
```
I am using `import { Link } from '@remix-run/react'` throughout my code for navigation.

When I load a page directly, it is properly caching
![image](https://github.com/user-attachments/assets/ab04b4aa-dbd6-4538-9b4a-6c43e53ba010)

However, when I navigate through the site, it always has cache misses
![image](https://github.com/user-attachments/assets/1b5df9f2-570d-4fdc-accb-4ad0bf087079)

If i directly hit `https://store-new-stage.nftreasure.com/?_data=routes%2F_index` etc through curl then it does cache, so it's only going through Remix Links that is causing the behavior. I can't find any information on this - can you help?

**Comment by joeykamsteeg** [comment]
Do you also return the headers from your loader?

**Comment by TooTallNate** [comment]
@mikkel-arturo Did you figure this out? I see it as a cache HIT now.

<img width="425" alt="Screenshot 2024-10-22 at 09 43 35" src="https://github.com/user-attachments/assets/b122de67-28af-49c0-93d2-1122af096d84">

**Comment by TooTallNate** [comment]
No response, closing for now.
