### ISSUE TITLE
Support Remix v2.13.1 for Edge functions

### ISSUE THREAD

**Issue by janhesters** [vercel/remix#137]
Remix recently released [2.13.1](https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v2131) stabilizing many future flags.

Please add support for it on edge functions 🙏

**Comment by chinanderm** [comment]
@TooTallNate Please cut a new release so us using Vercel to host Remix projects can upgrade to Remix v2.13.1.

**Comment by chinanderm** [comment]
Thank you @TooTallNate!
