### ISSUE TITLE
React-Router v7 compatibility?

### ISSUE THREAD

**Issue by linobino1** [vercel/remix#141]
Now that React-Router v7 is released and is the de-facto version 3 of Remix, will you adopt this template to work with RR v7?

**Comment by paul-vd** [comment]
I think a new version of this package should be created `@vercel/react-router`?

@TooTallNate any plans for this already?

**Comment by paul-vd** [comment]
I see that there is a template in the react-router git: https://github.com/remix-run/react-router-templates/tree/main/vercel

Does this mean we no longer need this package? or does this package still achieve additional requirements for vercel deployments?

**Comment by joeykamsteeg** [comment]
Would be nice if we could hear something from Vercel

**Comment by chinanderm** [comment]
@TooTallNate Any update you can share here? Even a "we're discussing internally" is fine. I think folks here would just like _some_ word from Vercel. Thanks.

**Comment by leerob** [comment]
Hey y'all – we're tracking support requests here for this https://vercel.community/t/support-for-react-router-7/2769. Let's move the conversation there 😄 

Definitely want to add support for RRv7 in the future!

**Comment by serranoarevalo** [comment]
@leerob Any rough ETA on this?

**Comment by nischayv** [comment]
Any updates on this? Would be massively helpful to have an ETA!

**Comment by parweb** [comment]
still no news ?

**Comment by hubciorz** [comment]
Any news... ?

**Comment by visormatt** [comment]
For folks not following the [Vercel Support thread](https://vercel.community/t/support-for-react-router-7/2769/29) it looks like a preset has shipped

**Comment by TooTallNate** [comment]
Hello! React Router v7 support has shipped, please see the changelog https://vercel.com/changelog/support-for-react-router-v7
