### ISSUE TITLE
Edge routes are overwriting serverless routes when there's a potential overlap

### ISSUE THREAD

**Issue by hdoro** [vercel/remix#20]
Let's say we have the following two routes (using route conventions v1, not sure how it'd behave with v2):

1. `routes/$.tsx` - `runtime: 'edge'`
2. `routes/manage/$.tsx` - `runtime: 'serverless'`

By Remix's standards, requests to `site.com/manage` should call `routes/manage/$.tsx`, which means using the serverless runtime.

However, in the set-up above, Vercel is using the `routes/manage/$.tsx` route but with the `edge` runtime, which breaks it. Here are the logs:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/27744332/227207822-4f9c4cbd-f502-452c-8439-914f1b031704.png">

This is fixed if I duplicate `routes/manage/$.tsx` as `routes/manage/index.tsx`.

**Comment by TooTallNate** [comment]
Thanks for the report, and confirmed that this is a bug.

Can you try creating a deployment with this env var set to confirm my fix? `VERCEL_CLI_VERSION=https://vercel-git-tootallnate-vccli-637-parent-catch-all-route-06c5fb.vercel.sh/tarballs/vercel.tgz`

**Comment by TooTallNate** [comment]
Fixed in [Vercel CLI 28.18.1](https://github.com/vercel/vercel/releases/tag/vercel%4028.18.1).
