### ISSUE TITLE
Support for v2_routeConvention?

### ISSUE THREAD

**Issue by jgentes** [vercel/remix#24]
I'm using `"@vercel/remix": "^1.14.3-patch.1"`, and while `remix dev` works fine locally, when I deploy to Vercel I just get `Code: FUNCTION_INVOCATION_TIMEOUT`.

The logs just show a GET request so I can't tell what the actual error is.

Feel free to clone the repo and give it a try: https://github.com/jgentes/mixpoint

I'm wondering if it's due to the new `v2_routeConvention` support that I have enabled in the `remix.config.js` file?

**Comment by TooTallNate** [comment]
`v2_routeConvention` should be working. We have a test for it. I did notice an issue with your lockfile where the wrong version of `@vercel/remix` was being installed.

I updated all `@remix-run/*` and `@vercel/remix` dependencies to `1.15.0` and it seems to deploy successfully: https://mixpoint-77bxxyqk0.vercel-support.app/

**Comment by jgentes** [comment]
Thanks for the quick response! I deleted my `node_modules` and `yarn_lock` then updated my dependencies to 1.15, however I see the same problem. 

I also deleted my app on Vercel and re-deployed, but no go.

Did you change any of the build settings? I went with defaults for Remix.

**Comment by jgentes** [comment]
Nevermind, I reverted back to my earlier codebase, then made the updates, and now it appears to be working. Thanks!
