### ISSUE TITLE
Edge routes with emotion

### ISSUE THREAD

**Issue by ilijaNL** [vercel/remix#48]
Hello, 

I am trying to get emotion (mantine ui) working inside a route which is using edge runtime, however since emotion ssr is using some native nodejs modules (stream/buffer) I am kinda stuck. According to this gh comment https://github.com/remix-run/remix/issues/2813#issuecomment-1685485736, remix does polyfills when targeting non nodejs environments and I wonder if this is still true? Currently when I am trying to deploy vercel I get the following error:

```
Error: The Edge Function "layout/:id" is referencing unsupported modules:
        - duplexer2: ./internal/streams/stream, stream
        - html-dom-parser: ./index.js
        - multipipe: stream
        - readable-stream: stream
        - through: stream
```

In the end I just want to get emotion SSR working on an edge runtime. What is the best solution to do this?

**Comment by TooTallNate** [comment]
If Emotion is using Node.js-specific APIs then it won't work on Edge runtime. You would need to ask them to enable support for that. Looks like there is a relevant conversation [here](https://github.com/emotion-js/emotion/issues/2446).
