### ISSUE TITLE
Error [ERR_MODULE_NOT_FOUND]: Cannot find module

### ISSUE THREAD

**Issue by benjaminleonard** [vercel/remix#59]
Same issue as here: https://github.com/vercel/vercel/issues/10494

It's working locally and on fly but not on Vercel. Running Remix@2.0.1

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js' imported from /var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Any ideas? I've migrated over to ESM, and I'd assume it's an issue with my project but it looks like it's happening in a fresh project too based on that issue.

**Comment by TooTallNate** [comment]
Can you share a repository demonstrating this happening?

**Comment by benjaminleonard** [comment]
Invited you to the repo, it's on the `remix-esm-v2` branch. Hope that's okay, I've been unable to reproduce on a fresh installation.

**Comment by benjaminleonard** [comment]
Unsure if it's connected but the function file sizes are dramatically smaller on the ESM build that is not working:

CJS:
<img width="1128" alt="image" src="https://github.com/vercel/remix/assets/4020798/aaa0b079-b2f7-4530-98c3-3f6950148286">

ESM:
<img width="1129" alt="image" src="https://github.com/vercel/remix/assets/4020798/407220c1-5e04-4c4a-b7dc-a0d78816d046">

**Comment by TooTallNate** [comment]
Hey @benjaminleonard, sorry, I lost track of this one. Were you still having issues?

For future reference, it would be better to [create a support ticket](https://vercel.com/help#issues) so that it gets properly tracked.

**Comment by benjaminleonard** [comment]
Switching `remix.config.ts` to `js` fixes my issue. #64 
Will close this.

> For future reference, it would be better to [create a support ticket](https://vercel.com/help#issues) so that it gets properly tracked.

Noted, thanks!

**Comment by TooTallNate** [comment]
Thanks for the confirmation! I don't believe `.ts` is a supported file extension for the remix.config file (https://github.com/remix-run/remix/discussions/2934, https://github.com/remix-run/remix/pull/438).
