### ISSUE TITLE
Support bundling with `unstable_vitePlugin` introduced in remix v2.2 

### ISSUE THREAD

**Issue by mmachatschek** [vercel/remix#63]
Official Vercel Remix v2.2 support for the newly introduced unstable vite plugin would be great

**Comment by EndangeredMassa** [comment]
@mmachatschek we're looking into, thanks!

**Comment by 684efs3** [comment]
That's good - looking forward to it!

**Comment by sigma-andex** [comment]
@EndangeredMassa do you have a timeline for this? Seems right now remix doesn't work on vercel even without vite (see #59 - having the same error).

**Comment by EndangeredMassa** [comment]
The https://github.com/vercel/remix/issues/59 issue was just resolved. Let us know if you are still seeing that issue.

We do not have a timeline for the vite plugin support, but it is a priority.

**Comment by 684efs3** [comment]
For the vite plugin support, is this something like a week, a month, several months? Ballpark would be great. Thank you!

**Comment by mmachatschek** [comment]
FYI the remix roadmap tracks a new feature [Bundle Shredding 🎸 for Lambda/Serverless Architecture](https://github.com/orgs/remix-run/projects/5?pane=issue&itemId=43815635). With that it should be able to output the built remix production code in a format that is supported by the Vercel build API.

I think this would make the `@vercel/remix` plugin obsolete and add native serverless/edge function support from the remix side 🤔

**Comment by 684efs3** [comment]
Very interesting! That would make it easier to deploy on Cloudflare too right?

**Comment by john-griffin** [comment]
Spotted this work around https://www.youtube.com/watch?v=oYmjsWjoFB0

**Comment by mitchelvanbever** [comment]
Any updates?

**Comment by EndangeredMassa** [comment]
> For the vite plugin support, is this something like a week, a month, several months? Ballpark would be great. Thank you!

It's not likely to come in the next month. We very much want to get to this as soon as we can.

**Comment by 684efs3** [comment]
Thank you for the update!

**Comment by swamidass** [comment]
Any progress here?

ALSO, note that the vite builder rejects Vercel's approach to specifying edge routes:

`export const config = { runtime: 'edge' };`

That does NOT work on the vite build, which only allows whitelisted (i.e. remix) exports from routes. Some sort of work around is needed.

**Comment by EndangeredMassa** [comment]
This is still in the list of projects we want to tackle next. We'll make an announcement when it's done, but we have other things we need to tackle first.

**Comment by jgentes** [comment]
> FYI the remix roadmap tracks a new feature [Bundle Shredding 🎸 for Lambda/Serverless Architecture](https://github.com/orgs/remix-run/projects/5?pane=issue&itemId=43815635). With that it should be able to output the built remix production code in a format that is supported by the Vercel build API.
> 
> I think this would make the `@vercel/remix` plugin obsolete and add native serverless/edge function support from the remix side 🤔

Looks like Bundle Shredding (now called Server Bundles) was completed yesterday: https://github.com/remix-run/remix/issues/8296

Any word on how this might impact Vite + Remix support on Vercel?

**Comment by mmachatschek** [comment]
It looks like there is some progress here https://github.com/vercel/vercel/pull/11031

**Comment by EndangeredMassa** [comment]
> Any word on how this might impact Vite + Remix support on Vercel?

We are exploring it, but no ETA just yet.

**Comment by justyn-clark** [comment]
If we can't get this soon then I'm going to have to migrate back over to Railway.app and/or Fly.io. I wish Vercel would just let us deploy Docker images.

**Comment by sigma-andex** [comment]
> If we can't get this soon then I'm going to have to migrate back over to Railway.app and/or Fly.io. I wish Vercel would just let us deploy Docker images.

I feel you! Also thinking about switching to cloudflare because of this.

**Comment by okalil** [comment]
I think this issue deserves more attention now that [remix vite plugin is stable](https://remix.run/blog/remix-vite-stable) and will become the default soon.

**Comment by justyn-clark** [comment]
> > If we can't get this soon then I'm going to have to migrate back over to Railway.app and/or Fly.io. I wish Vercel would just let us deploy Docker images.
> 
> I feel you! Also thinking about switching to cloudflare because of this.

That's not a bad idea and I've been temped as well as I have pending DNS switch overs to Cloudflare waiting for me to disconnect from Vercel and press go. From my observations, Remix and CF is a solid reliable pairing and apps serve fast from Workers and Pages. Actually might be a safer bet just in case Vercel pulls some marketing stunts down the road that makes things more difficult for devs when as they continue seeking profit. 

But @sigma-andex have no fear. I'm happy to share that have and am successfully deploying Vite Remix to Vercel serverless, and it's working pretty damn good. 

All thanks to our hero and single most influential contributor to version 2.7.2 bringing us the stable Vite Remix.

Just pre-build that shit and deploy it from your local IDE. Bypass even dealing with the Vercel website in fact.  https://vercel.com/docs/cli/deploy

Here's the stuff.
https://github.com/hi-ogawa/remix-vite-deployment-examples

Thank you [hi-ogawa](https://github.com/hi-ogawa/)! Really appreciate you contributions here.

**Comment by itzcull** [comment]
@justyn-clark your example is great, unblocked me!

**Comment by TooTallNate** [comment]
We are getting closer to announcing our Remix + Vite support on Vercel. If you would like to help test, I've posted some instructions on how to do so [here](https://github.com/vercel/vercel/pull/11031).

**Comment by justyn-clark** [comment]
> We are getting closer to announcing our Remix + Vite support on Vercel. If you would like to help test, I've posted some instructions on how to do so [here](https://github.com/vercel/vercel/pull/11031).

Done deal. My tests passed.
https://github.com/vercel/vercel/pull/11031#issuecomment-1967814302

**Comment by TooTallNate** [comment]
[Remix + Vite + Vercel is now stable](https://vercel.com/changelog/support-for-remix-with-vite).

**Comment by olros** [comment]
Just tested Remix + Vite + Vercel, but `WARN: Vercel uses its own `enter.server` file, so the file "app/entry.server.tsx" has been deleted.` cause problems for me. I'm using MUI components which uses emotion for styling. According to the [Remix example app with emotion](https://github.com/remix-run/examples/tree/main/emotion), custom `entry.client.tsx` and `entry.server.tsx` is required to inject styles correctly. Is there any way provide my own `entry.server.tsx`-file?

**Comment by k1sul1** [comment]
>  Is there any workaround which allows me to provide my own `entry.server.tsx`-file?

Same problem with Sentry. 

https://docs.sentry.io/platforms/javascript/guides/remix/manual-setup/

**Comment by TooTallNate** [comment]
Heard. I'm working on a fix for that. Stay tuned.

**Comment by TooTallNate** [comment]
@olros @k1sul1 Follow along in https://github.com/vercel/remix/pull/89.
