### ISSUE TITLE
Using typescript for `remix.config` breaks deployment.

### ISSUE THREAD

**Issue by sigma-andex** [vercel/remix#64]
Using typescript for `remix.config` breaks the deployment:
```
500: INTERNAL_SERVER_ERROR Code: FUNCTION_INVOCATION_FAILED
```
Using `remix.config.ts` works fine locally and also builds on vercel.

This is possibly related to #59 (at least I get the same error `Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-<hash>.js' imported from /var/task/build/server-build-nodejs-<hash>.mjs` in the logs). 
Switching to `remix.config.js` solved the issue.

A minimal reproducible example can be found here: https://github.com/expln-ai/remix-tutorial
-> [`remix.config.js`](https://github.com/expln-ai/remix-tutorial/blob/main/_remix.config.js) works
-> [`remix.config.ts`](https://github.com/expln-ai/remix-tutorial/blob/main/remix.config.ts) doesn't

**Comment by benjaminleonard** [comment]
Oh nice find! Changing to `js` fixes my issue

**Comment by TooTallNate** [comment]
I'm not seeing anywhere in the Remix docs that `.ts` is supported for the `remix.config` file. Correct me if I'm wrong (https://github.com/remix-run/remix/discussions/2934, https://github.com/remix-run/remix/pull/438).

**Comment by TooTallNate** [comment]
Looks like only `.js`, `.cjs`, or `.mjs` are valid: https://github.com/remix-run/remix/blob/723abde3a79f67af944fe98ff5101c588b9153ec/packages/remix-dev/config.ts#L669-L683

**Comment by sigma-andex** [comment]
> I'm not seeing anywhere in the Remix docs that `.ts` is supported for the `remix.config` file. Correct me if I'm wrong ([remix-run#2934](https://github.com/remix-run/remix/discussions/2934), [remix-run#438](https://github.com/remix-run/remix/pull/438)).

Oh I see. I just used it and it worked locally, so didn't pay attention to whether it was officially supported or not.

**Comment by TooTallNate** [comment]
It "worked" but was just using the default values that Remix uses. If you had tried to change anything in that configuration, those values would not have been picked up.
