### ISSUE TITLE
Asset path broken for some assets

### ISSUE THREAD

**Issue by sigma-andex** [vercel/remix#80]
I'm trying to deploy a remix app (2.6.0) to vercel, but for some reason the assets are deployed to `/build/vercel/path0/_assets/` and `/build/_assets/`.  Unfortunately though, some of the assets (some pngs, but not all) are **only** deployed to `/build/vercel/path0/_assets/` and therefore not found on my website. I have no idea why this happens and why it is only some of the pngs but not all. I have them in `/app/assets` but also tried `/public` and next to the importing tsx file.

**Comment by EndangeredMassa** [comment]
@sigma-andex can you share an example of this happening? IT could be your current project or a trimmed down version that reproduces the issue?

**Comment by lifeiscontent** [comment]
I'm seeing something similar, I'm importing files from the root index path, and a few other pages under `/platforms/example` I'm seeing `/platforms` being prepended to the asset url path on the `/platforms/example` page

**Comment by lifeiscontent** [comment]
CC: @TooTallNate

**Comment by TooTallNate** [comment]
@lifeiscontent Ya I can reproduce. We're looking into it. For now, just put in `public` instead and use a string for the `src`.

**Comment by TooTallNate** [comment]
@lifeiscontent I can not reproduce. Can you share your repository?

**Comment by lifeiscontent** [comment]
@TooTallNate yep, I'll put something together in the next hour or so. Thanks!

**Comment by lifeiscontent** [comment]
@TooTallNate I actually ended up figuring this out, I guess with vite, url handling is a little bit different, if I add a `/` to the `_vercel/image?` path things work again. That being said, any chance you guys will be adding support for https://github.com/vercel/remix/issues/65 or at the very least do you have any recommendations on the code I've provided in that PR to better utilize Vercel's image optimization service?

**Comment by TooTallNate** [comment]
Ok cool, sounds like this one can be closed then.

> That being said, any chance you guys will be adding support for https://github.com/vercel/remix/issues/65 or at the very least do you have any recommendations on the code I've provided in that PR to better utilize Vercel's image optimization service in a more DX friendly way?

Yes, I would like to add support for this. Follow the original issue for updates.
