### ISSUE TITLE
Unable to build Remix Project using new Vite Preset

### ISSUE THREAD

**Issue by robipop22** [vercel/remix#87]
Hello everyone, 

I tried to update to latest packages 2.8.0, build and deploy the dnb-stack to Vercel https://github.com/robipop22/dnb-stack/tree/dev

The local development works fine, but is the vercel build which is failing.

Even locally, weirdly Vercel build removes @remix-run/dev and installs @vercel-remix-run-dev so the build is failing because in vite.confgi.ts I am trying to import the @remix-run/dev package which is now removed.

`Installing dependencies...
 WARN  2 deprecated subdependencies found: loupe@2.3.6, source-map-resolve@0.6.0
Packages: +2 -3
++---`

```
devDependencies:
- @remix-run/dev 2.8.0
+ @vercel/remix-run-dev 2.8.0
```

`Error: Cannot find module '@remix-run/dev'`

Code is available on the `dev` branch on dnb-stack.

Any help/guidance is appreciated.

Thanks

**Comment by TooTallNate** [comment]
Delete `remix.config.js`. We are going to improve the heuristics for detecting if the project is using Vite.

**Comment by robipop22** [comment]
Confirming its working now.

Thanks !
