### ISSUE TITLE
How to replace entry.client.tsx/entry.server.tsx?

### ISSUE THREAD

**Issue by Gbuomprisco** [vercel/remix#88]
Not an issue per se - but I think we'll all encounter this issue: is it possible to use our own entry points? I use this for i18n/bot and haven't really found a solution for replacing them.

My builds are failing, and I suspect it's because I provided these files which the docs say should be deleted instead.

Any pointer would be really appreciated.

**Comment by TooTallNate** [comment]
There's discussion happening around this in https://github.com/vercel/remix/pull/85, so I'll close this one to keep the discussion in one place.
