### ISSUE TITLE
Bug: Error in `edge/index.ts` while importing `entry.server.js`

### ISSUE THREAD

**Issue by Aulos** [vercel/remix#91]
I tired to migrate my project to Vite, but I'm getting this error:

``` 
Error: [commonjs--resolver] Server-only module referenced by client

    './entry.server.js' imported by 'node_modules/@vercel/remix/dist/edge/index.js'

  See https://remix.run/docs/en/main/future/vite#splitting-up-client-and-server-code
```

It's happening regardless if I'm using edge runtime or not.

**Comment by Aulos** [comment]
It was because of cyclic import - not sure why it worked with the old builder.

**Comment by Aulos** [comment]
I had some kind of indirect dependency - I was using an util function in root that used another util which used something defined in root. I don't remember the specifics :( Sorry.

**Comment by zipme** [comment]
> I had some kind of indirect dependency - I was using an util function in root that used another util which used something defined in root. I don't remember the specifics :( Sorry.

I found a similar issue https://github.com/vercel/remix/issues/97#issuecomment-2016954513  followed the instruction tehre I managed to find the cause 😆

**Comment by Aulos** [comment]
Yeah, you can also try `vite-env-only` and define function in the same file: 
```ts
import { serverOnly$ } from "vite-env-only/macros";

const someActionFunction = serverOnly$(defineAction(...))
```
