### ISSUE TITLE
need `getLoadContext`

### ISSUE THREAD

**Issue by HananoshikaYomaru** [vercel/remix#92]
as title

https://remix.run/docs/en/main/route/loader#context

**Comment by TooTallNate** [comment]
What is the use case?

**Comment by HananoshikaYomaru** [comment]
the use case is to give a global data to every loader and action

**Comment by TooTallNate** [comment]
Can you put it in a file and import instead?

```typescript
// global-data.server.ts
export const data = { ... };
```

```
// app/routes/page.tsx
import { data } from '~/global-data.server';

export function loader() {
  // use `data
}
```

**Comment by Jarrku** [comment]
Our use case for getLoadContext is:
- Generating a logger instance bound to a request, so logs are grouped on initial SSR render based on this reuest id across loaders. 
- Access token manager shared across loaders, so they can request a new token if needed once, and not for every single loader.

In short, having a way to share a context across multiple loaders when they run in parallel on initial render.

As far as I understand, this will be solved in the future with the [server context proposal](https://github.com/remix-run/remix/discussions/7644), but for now it worked nicely.

**Comment by HananoshikaYomaru** [comment]
the reason why `getLoadContext` is a function is that it needs to fetch data but not a static data

**Comment by TooTallNate** [comment]
The purpose of the `getLoadContext()` function is to [pass through data from the server/platform layer](https://remix.run/docs/en/main/route/loader#context). In the case of Vercel, there is no data at the platform layer to pass through, which is why a `server.js` file is not supported in Remix + Vite. The docs also mention it is not recommended to use.

For data bound to the `Request` instance, you could use a `WeakMap` which stores value you are associating with the Request. Something like:

```typescript
// logger.server.ts
const loggers = new WeakMap<Request, Logger>();

export function getLogger(req: Request) {
  let logger = loggers.get(req);
  if (!logger) {
    logger = new Logger();
    loggers.set(req, logger);
  }
  return logger;
}
```

```typescript
// app/routes/page.tsx
import { getLogger } from '~/logger.server';

export function loader({ req }) {
  let logger = getLogger(req);
  logger.log('blah');
}
```

The same technique could be used for an async operation, like your token use-case:

```typescript
// token.server.ts
const tokens = new WeakMap<Request, Promise<Token>>();

export function getToken(req: Request) {
  let token = tokens.get(req);
  if (!token) {
    token = fetchOrRevalidateToken(req);
    tokens.set(req, token);
  }
  return token;
}
```

```typescript
// app/routes/page.tsx
import { getToken } from '~/token.server';

export function loader({ req }) {
  let token = await getToken(req);
}
```

All loaders will wait on the same Promise.

I'd argue this is a better technique than `getLoadContext()` because it's more explicit which data the loader needs, and so it won't need to fetch data that potentially would not be used in a given loader, whereas `getLoadContext()` doesn't know which data the loaders actually need and need to load everything.

**Comment by TooTallNate** [comment]
Here's a utility function you could use to make this pattern easier:

```typescript
export function weakCache<K extends object, V>(get: (key: K) => V) {
    let map = new WeakMap<K, V>();
    return (key: K) => {
        let v = map.get(key);
        if (!v) {
            v = get(key);
            map.set(key, v);
        }
        return v;
    }
}
```

Example Usage:

```typescript
export const getLogger = weakCache((req: Request) => new Logger());

export const getToken = weakCache(async (req: Request) => {
  let token = await fetchOrRevalidateToken(req);
  return token;
});
```

**Comment by TooTallNate** [comment]
I'll close this one considering the recommended alternative. Thanks for bringing this up!

**Comment by TooTallNate** [comment]
> If you have nested routes that use the token, it'll trigger the revalidation multiple times in parallel.

This should not be the case. Did you try it out? The `fetchOrRevalidateToken()` function in the example should be called _at most_, once per HTTP request. If you are seeing more, then there's a bug in my helper function.

**Comment by depsimon** [comment]
Yes, here's a short repro of how I test. It's not Vercel specific of course.

https://stackblitz.com/edit/remix-run-remix-my85zy?file=app%2Froot.tsx

You can see in the console the following logs:

```
fetchOrRevalidateToken token-6507
fetchOrRevalidateToken token-39553
fetchOrRevalidateToken token-24508
getToken token-6507
getToken token-39553
getToken token-24508
root [ 'token-6507', 'token-6507', 'token-6507' ]
_app [ 'token-39553', 'token-39553', 'token-39553' ]
_app.index [ 'token-24508', 'token-24508', 'token-24508' ]
```
