### ISSUE TITLE
Links have stopped working after deploy

### ISSUE THREAD

**Issue by lifeiscontent** [vercel/remix#98]
I can give access to the repo that I'm seeing this behavior in, but no matter what I do I can't seem to navigate to another page. https://remix-vcard.vercel.app after login, if you click the edit icon, it goes no where, but you can clearly see it links somewhere else.

**Comment by TooTallNate** [comment]
Sure, give me access please.

**Comment by lifeiscontent** [comment]
@TooTallNate done: https://github.com/lifeiscontent/remix-vcard/invitations let me know if you need anymore context. Happy to chat on Discord lifeiscontent is my username

**Comment by lifeiscontent** [comment]
@TooTallNate any updates here?

**Comment by lifeiscontent** [comment]
@TooTallNate I figured it out, I had a `overrides` key in my package.json mapping to the canary version of react that I committed during experimentation, that completely broke everything 😅

**Comment by lifeiscontent** [comment]
@TooTallNate nevermind, it was a combination of things, I think what is happening is the vercel adapater isn't doing something it should with the .server / .client folders in remix + vite, after I migrated all my code to .server this issue appeared.

**Comment by lifeiscontent** [comment]
there also seems to be an issue with using Prisma, that actually might be the root of the issue I'm seeing.

**Comment by lifeiscontent** [comment]
Okay, I finally figured out what my issue was. It was Prisma! The solution in this discussion fixed my issue:

https://github.com/prisma/prisma/discussions/20200
